import type { HeroDefinition, HeroId, PlayerBuffs } from "./types";

export const TARGETED_SKILL_HEROES: readonly HeroId[] = ["ashe", "teemo", "caitlyn"];

export const EMPOWER_BUFF_BY_HERO: Partial<Record<HeroId, keyof PlayerBuffs>> = {
  garen: "garen",
  yasuo: "yasuo",
  jinx: "jinxBomb",
  azir: "azir",
  pantheon: "pantheonPairBeatsSingle",
};

export const HEROES: readonly HeroDefinition[] = [
  {
    id: "garen",
    name: "盖伦",
    city: "德玛西亚",
    mark: "D",
    color: "#487487",
    skillName: "审判",
    skillSummary: "下一次出牌若为单牌或对子，比较点数 +1。",
    skillDescription: "发动后，你的下一次出牌若为单牌或对子，比较点数 +1；其他牌型不会获得加成。",
    fieldName: "坚毅阵线",
    fieldSummary: "地主第一次被压制后立即重新行动。",
    fieldDescription: "地主第一次被其他玩家压过时，不按常规顺序轮转，地主立即获得一次行动权。",
  },
  {
    id: "darius",
    name: "德莱厄斯",
    city: "诺克萨斯",
    mark: "N",
    color: "#8b4247",
    skillName: "诺克萨斯断头台",
    skillSummary: "下一次压过别人后，弃掉一张最小手牌。",
    skillDescription: "发动后，本局下一次成功压过其他玩家时，自动将自己点数最小的一张手牌放入弃牌区。",
    fieldName: "铁血竞技",
    fieldSummary: "炸弹或火箭出现时，倍率额外 +1。",
    fieldDescription: "每次有人打出炸弹或火箭，除牌型本身的倍率提升外，结算倍率再额外增加 1。",
  },
  {
    id: "ashe",
    name: "艾希",
    city: "弗雷尔卓德",
    mark: "F",
    color: "#4c7891",
    skillName: "魔法水晶箭",
    skillSummary: "选择一名敌方，使其下次实际出牌只能选单牌。",
    skillDescription: "选择一名敌方；该玩家下一次实际出牌只能打单牌，也可以过牌。过牌不会消耗冻结。",
    fieldName: "极寒律令",
    fieldSummary: "每轮首家不能打出炸弹或火箭。",
    fieldDescription: "每个出牌轮次的第一手牌不能是炸弹或火箭；顺序重置后再次生效。",
  },
  {
    id: "jinx",
    name: "金克丝",
    city: "祖安",
    mark: "Z",
    color: "#8c4d7a",
    skillName: "超究极死神飞弹",
    skillSummary: "下一组三张 3–10 可视为炸弹。",
    skillDescription: "发动后，下一次由三张相同点数且点数在 3–10 之间的牌组成的牌型，可以作为炸弹比较。",
    fieldName: "失控爆燃",
    fieldSummary: "炸弹后，下一家有牌可出时不能过牌。",
    fieldDescription: "炸弹或火箭出现后，下一名玩家若存在合法压制牌则不能过牌；确实无牌可出时允许过牌。",
  },
  {
    id: "caitlyn",
    name: "凯特琳",
    city: "皮尔特沃夫",
    mark: "P",
    color: "#75658e",
    skillName: "让子弹飞",
    skillSummary: "选择一名敌方，查看其随机三张手牌。",
    skillDescription: "选择一名敌方，查看最多三张随机手牌。信息保留到对应牌离开其手牌；仅施法者可见。",
    fieldName: "执法视野",
    fieldSummary: "地主首次过牌，公开两名农民各一张最大手牌。",
    fieldDescription: "地主本局第一次过牌时，公开两名农民各一张当时的最大手牌，保留到该牌离开其手牌。",
  },
  {
    id: "yasuo",
    name: "亚索",
    city: "艾欧尼亚",
    mark: "I",
    color: "#62815a",
    skillName: "踏前斩",
    skillSummary: "下一次顺子允许出现一个点数缺口。",
    skillDescription: "发动后，下一次顺子可以累计缺少一个点数；仍不能包含 2 或王，且需要满足场地规定的最小长度。",
    fieldName: "流风之地",
    fieldSummary: "顺子最少四张，连对最少两对。",
    fieldDescription: "所有玩家的顺子最小长度从五张降为四张，连对最小长度从三对降为两对。",
  },
  {
    id: "thresh",
    name: "锤石",
    city: "暗影岛",
    mark: "S",
    color: "#3f8276",
    skillName: "魂引之灯",
    skillSummary: "从已结算弃牌中选择一张 3–10，与一张手牌交换。",
    skillDescription: "选择一张已结算弃牌中的 3–10，再选择一张自己的手牌交换。不能取走当前领出牌，确认前可取消，手牌总数不变。",
    fieldName: "魂锁典狱",
    fieldSummary: "任意玩家首次降至三张及以下，公开其随机一张手牌。",
    fieldDescription: "每名玩家本局第一次降到三张及以下时，公开其随机一张手牌。所有对局都有一张、两张余牌提醒。",
  },
  {
    id: "azir",
    name: "阿兹尔",
    city: "恕瑞玛",
    mark: "A",
    color: "#a28741",
    skillName: "沙兵现身",
    skillSummary: "下一次对子可按三张比较。",
    skillDescription: "发动后，下一次打出的对子按同点数的三张比较；实际只消耗所选择的两张牌。",
    fieldName: "帝国军阵",
    fieldSummary: "地主首轮的三张可带零至两张牌。",
    fieldDescription: "地主本局第一次首出时，三张相同点数的牌可以不带牌、带一张或带两张，并按三张家族互相比较。",
  },
  {
    id: "pantheon",
    name: "潘森",
    city: "巨神峰",
    mark: "T",
    color: "#777590",
    skillName: "星陨冲击",
    skillSummary: "下一次对子可按单牌压制。",
    skillDescription: "发动后，下一次打出的对子按同点数单牌比较，实际会消耗两张牌。",
    fieldName: "不屈天穹",
    fieldSummary: "地主首次少于五张时获得防炸弹护盾。",
    fieldDescription: "地主首次降至五张以下获得本局护盾；仅地主领出的牌免受普通炸弹压制，火箭仍有效。",
  },
  {
    id: "missfortune",
    name: "厄运小姐",
    city: "比尔吉沃特",
    mark: "B",
    color: "#9a5547",
    skillName: "枪林弹雨",
    skillSummary: "与每名敌方各随机交换一张牌。",
    skillDescription: "与每名敌方各随机交换一张牌：交出自己当前最小手牌，换入一张随机敌方手牌。不会交换队友的牌。",
    fieldName: "海盗分赃",
    fieldSummary: "地主领出后两名农民都过牌，地主弃最小牌。",
    fieldDescription: "当地主是当前领出者且两名农民连续过牌结束本轮时，地主自动弃掉一张点数最小的手牌。",
  },
  {
    id: "teemo",
    name: "提莫",
    city: "班德尔城",
    mark: "Y",
    color: "#6f843e",
    skillName: "种蘑菇",
    skillSummary: "选择一名敌方，其下次普通出牌比较点数 −1。",
    skillDescription: "选择一名敌方，其下一次普通出牌比较点数 −1，实际牌面不变。过牌、炸弹和火箭不消耗标记。",
    fieldName: "约德尔恶作剧",
    fieldSummary: "每轮最后过牌者下次行动不能使用技能。",
    fieldDescription: "一轮因连续两次过牌而结束时，最后一名过牌者会在下一次行动中被禁止使用技能。",
  },
  {
    id: "kaisa",
    name: "卡莎",
    city: "虚空",
    mark: "V",
    color: "#704f89",
    skillName: "虚空索敌",
    skillSummary: "吞噬一张最小手牌，倍率最低降至 1。",
    skillDescription: "将自己点数最小的一张手牌直接放入弃牌区，并让当前结算倍率减少 1，但不会低于 1。",
    fieldName: "虚空干扰",
    fieldSummary: "地主首次少于五张时，一名农民下次不能出炸弹。",
    fieldDescription: "地主第一次将手牌降到五张以下时，随机标记一名农民；其下一次实际出牌不能使用炸弹或火箭。",
  },
] as const;

export const HERO_BY_ID = Object.fromEntries(HEROES.map((hero) => [hero.id, hero])) as Record<HeroId, HeroDefinition>;

export const GUIDE_STEPS = [
  { title: "三人牌桌", body: "你在底部，两名 AI 位于牌桌上方。座位标明敌我、余牌与状态。中央显示目标牌型、已知牌和最近行动。" },
  { title: "抢地主", body: "抢地主不设叫分。你抢地主时直接获得三张底牌；不抢时由两名 AI 根据手牌和确定性随机结果决定。" },
  { title: "选牌与出牌", body: "点击卡牌或用方向键移动焦点，Enter/Space 选牌。P 出牌、H 提示、X 不要，Esc 清空选牌。" },
  { title: "英雄与城邦", body: "英雄主动技能每局只能发动一次；只有地主英雄所绑定的城邦被动会在牌局中生效。" },
  { title: "横屏体验", body: "窄屏横屏可以水平浏览手牌，键盘焦点会自动滚入可视范围；竖屏会暂停 AI 并显示旋转提示。" },
  { title: "本作牌规", body: "支持单牌、对子、三张、三带一/对、顺子、连对、连续三张、飞机带单/对、四带两单/两对及炸弹、火箭。顺子、连续主体不含 2 和王；翅膀不复用主体点数。" },
  { title: "翅膀与倍率", body: "飞机单翅可同点数，但不能同时携带双王；四带两单可带对子，也不能携带双王，四带两对须不同点数。本作简化抢地主，普通炸弹倍率 +1，火箭 +2；积分按地主 20、农民各 10 乘最终倍率结算。" },
] as const;

export function isHeroId(value: string): value is HeroId {
  return Object.hasOwn(HERO_BY_ID, value);
}
